-- 0002_inference.sql
-- Migration to support RetailMind Inference Service

-- Table to store metadata about uploaded datasets
CREATE TABLE IF NOT EXISTS datasets (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT,
  source        TEXT NOT NULL,                 -- 'upload' | 'seed' | 'api'
  content_hash  TEXT NOT NULL UNIQUE,          -- sha256 of transaction data
  row_count     INTEGER NOT NULL,
  customer_count INTEGER NOT NULL,
  uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  uploaded_by   TEXT
);

-- Table to store calibration profiles generated by the Python inference service
CREATE TABLE IF NOT EXISTS dataset_profiles (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  dataset_id    UUID NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
  model_version TEXT NOT NULL,
  profile       JSONB NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (dataset_id, model_version)
);

-- Add dataset_id to customer_segments to track which dataset generated the current score
-- Note: customer_id remains the primary key for current state
ALTER TABLE customer_segments
  ADD COLUMN IF NOT EXISTS dataset_id UUID REFERENCES datasets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS explanation TEXT;

CREATE INDEX IF NOT EXISTS idx_customer_segments_dataset ON customer_segments(dataset_id);
